name: Artifact Example - Incomplete Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Step
        id: build
        run: |
          echo "This is the build output." > build-output.txt

      - name: Upload Build Output
        uses: actions/upload-artifact@v4
        with:
          name: build-outputv2
          path: build-output.txt


  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Output
        uses: actions/download-artifact@v4
        with:
          name: build-outputv2
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Build Output
        run: |
            cat build-output.txt
