name: CI Minimal

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Vérifier le repo
        uses: actions/checkout@v4

      - name: Afficher un message
        run: echo "Hello CI"
